"""add topic_list to interviews

Revision ID: 4f6487111b0c
Revises: 03d6915351aa
Create Date: 2026-07-07 13:18:22.038016

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4f6487111b0c"
down_revision: Union[str, Sequence[str], None] = "03d6915351aa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "interviews",
        sa.Column("topic_list", sa.JSON(), nullable=False, server_default="[]"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("interviews", "topic_list")
    # ### end Alembic commands ###
