"""create_interviews_table

Revision ID: b71f946cb9e8
Revises: cae64f029cac
Create Date: 2026-07-04 23:05:36.899481

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b71f946cb9e8"
down_revision: Union[str, Sequence[str], None] = "cae64f029cac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "interviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("current_topic", sa.String(length=255), nullable=True),
        sa.Column("remaining_topics", sa.JSON(), nullable=False),
        sa.Column("current_question", sa.String(length=1000), nullable=True),
        sa.Column("follow_up_count", sa.Integer(), nullable=False),
        sa.Column("history", sa.JSON(), nullable=False),
        sa.Column("remaining_time", sa.Integer(), nullable=False),
        sa.Column("interview_mode", sa.String(length=50), nullable=False),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_interviews_user_id"), "interviews", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_interviews_user_id"), table_name="interviews")
    op.drop_table("interviews")
    # ### end Alembic commands ###
